// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq8_i5nii55Yk-K8cCPNLYkK6XATh4GtA',
    appId: '1:504850521827:web:6234b7bc23dccb42a32fd6',
    messagingSenderId: '504850521827',
    projectId: 'flutter-firebase-auth-impl',
    authDomain: 'flutter-firebase-auth-impl.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-impl.appspot.com',
    measurementId: 'G-7ZF9EHXEBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCscQ20djsZTc4W-VFNxOGKndX9yYf-_3Q',
    appId: '1:504850521827:android:668bd6b92afeeea5a32fd6',
    messagingSenderId: '504850521827',
    projectId: 'flutter-firebase-auth-impl',
    storageBucket: 'flutter-firebase-auth-impl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE58VkbAM7O4mHZSlZLJm9fZQPBeVv_Qs',
    appId: '1:504850521827:ios:223c1faef0313b31a32fd6',
    messagingSenderId: '504850521827',
    projectId: 'flutter-firebase-auth-impl',
    storageBucket: 'flutter-firebase-auth-impl.appspot.com',
    iosBundleId: 'com.exampledomain.flutterFirebaseAuthImplementation',
  );
}
